from django.urls import path

from . import views

app_name = 'ss_activities'

urlpatterns = [
    path('visitas-grupos/', views.list_visitas_grupos, name='list_visitas_grupos'),
    path(
        'visitas-grupos/adicionar/',
        views.add_visita_grupo,
        name='add_visita_grupo',
    ),
    path(
        'visitas-grupos/<int:visita_id>/editar/',
        views.edit_visita_grupo,
        name='edit_visita_grupo',
    ),
    path(
        'visitas-grupos/<int:visita_id>/apagar/',
        views.delete_visita_grupo,
        name='delete_visita_grupo',
    ),
    path(
        'visitas-grupos/<int:visita_id>/pastoreio/',
        views.list_visitas_pastoreio,
        name='list_visitas_pastoreio',
    ),
    path(
        'visitas-grupos/<int:visita_id>/pastoreio/adicionar/',
        views.add_visita_pastoreio,
        name='add_visita_pastoreio',
    ),
    path(
        'visitas-grupos/<int:visita_id>/pastoreio/<int:pastoreio_id>/confirmar/',
        views.confirm_visita_pastoreio,
        name='confirm_visita_pastoreio',
    ),
    path(
        'visitas-grupos/<int:visita_id>/pastoreio/<int:pastoreio_id>/apagar/',
        views.delete_visita_pastoreio,
        name='delete_visita_pastoreio',
    ),
    path(
        'testemunho-publico/',
        views.painel_testemunho_publico,
        name='painel_testemunho_publico',
    ),
    path(
        'testemunho-publico/pdf/',
        views.pdf_testemunho_publico,
        name='pdf_testemunho_publico',
    ),
    path(
        'testemunho-publico/disponibilidade/',
        views.disponibilidade_testemunho_publico,
        name='disponibilidade_testemunho_publico',
    ),
    path(
        'testemunho-publico/designacoes/adicionar/',
        views.add_designacao_testemunho_publico,
        name='add_designacao_testemunho_publico',
    ),
    path(
        'testemunho-publico/designacoes/<int:designacao_id>/editar/',
        views.edit_designacao_testemunho_publico,
        name='edit_designacao_testemunho_publico',
    ),
    path(
        'testemunho-publico/designacoes/<int:designacao_id>/apagar/',
        views.delete_designacao_testemunho_publico,
        name='delete_designacao_testemunho_publico',
    ),
    path(
        'testemunho-publico/habilitados/',
        views.list_habilitados_testemunho_publico,
        name='list_habilitados_testemunho_publico',
    ),
    path(
        'testemunho-publico/habilitados/adicionar/',
        views.add_habilitado_testemunho_publico,
        name='add_habilitado_testemunho_publico',
    ),
    path(
        'testemunho-publico/habilitados/<int:item_id>/editar/',
        views.edit_habilitado_testemunho_publico,
        name='edit_habilitado_testemunho_publico',
    ),
    path(
        'testemunho-publico/periodos/',
        views.list_periodos_testemunho_publico,
        name='list_periodos_testemunho_publico',
    ),
    path(
        'testemunho-publico/periodos/adicionar/',
        views.add_periodo_testemunho_publico,
        name='add_periodo_testemunho_publico',
    ),
    path(
        'testemunho-publico/periodos/<int:item_id>/editar/',
        views.edit_periodo_testemunho_publico,
        name='edit_periodo_testemunho_publico',
    ),
    path(
        'testemunho-publico/locais/',
        views.list_locais_testemunho_publico,
        name='list_locais_testemunho_publico',
    ),
    path(
        'testemunho-publico/locais/adicionar/',
        views.add_local_testemunho_publico,
        name='add_local_testemunho_publico',
    ),
    path(
        'testemunho-publico/locais/<int:item_id>/editar/',
        views.edit_local_testemunho_publico,
        name='edit_local_testemunho_publico',
    ),
    path(
        'testemunho-publico/carrinhos/',
        views.list_carrinhos_testemunho_publico,
        name='list_carrinhos_testemunho_publico',
    ),
    path(
        'testemunho-publico/carrinhos/configuracao/',
        views.save_configuracao_testemunho_publico,
        name='save_configuracao_testemunho_publico',
    ),
    path(
        'testemunho-publico/carrinhos/<int:carrinho_id>/editar/',
        views.edit_carrinho_testemunho_publico,
        name='edit_carrinho_testemunho_publico',
    ),
]
